#!/usr/bin/env bash

#SBATCH --job-name=transformer_br_seed_2_42_alyx_job
#SBATCH --output=slurm_logs/transformer_br_seed_2_42_job_%j.txt
#SBATCH --error=slurm_logs/transformer_br_seed_2_42_job_error_%j.txt
#SBATCH --time=15:00:00
#SBATCH --partition=pgpu_most
#SBATCH --account=dei_most
#SBATCH --gpus=1
#SBATCH --mem=20G
#SBATCH --mail-type=NONE
#SBATCH --mail-user=davide.frizzo.1@studenti.unipd.it

echo "-------------------------------------------"
echo "Activating virtual environment"
echo "-------------------------------------------"

source ~/davide_frizzo/alyx-ssm/.venv/bin/activate

echo "-------------------------------------------"
echo "Starting alyx experiment"
echo "-------------------------------------------"

model_name="transformer"
data_encoding="br"
seed=42
data_dir="/home/u0052/datasets/alyx"
mode="multirun"

if [[ "$mode" == "multirun" ]]; then

  #WARN: Hard coded list of seed values changed to 2,42 in run-multi-exp-slurm, re change it
  ./run-multi-exp-slurm "$model_name" "$data_encoding" "$data_dir"

else

  ./run-exp-slurm "$model_name" "$data_encoding" $seed "$data_dir"

fi

