#!/usr/bin/env bash

#SBATCH --job-name=transformer_bra_alyx_job
#SBATCH --output=slurm_logs/transformer_bra_job_%j.txt
#SBATCH --error=slurm_logs/transformer_bra_job_error_%j.txt
#SBATCH --time=10:00:00
#SBATCH --partition=pgpu_most
#SBATCH --account=dei_most
#SBATCH --gpus=1
#SBATCH --mail-type=NONE
#SBATCH --mail-user=davide.frizzo.1@studenti.unipd.it

echo "-------------------------------------------"
echo "Activating virtual environment"
echo "-------------------------------------------"

source ~/davide_frizzo/alyx-ssm/.venv/bin/activate

echo "-------------------------------------------"
echo "Starting alyx experiment"
echo "-------------------------------------------"

device_num=0
model_name="transformer"
data_encoding="bra"

./run-exp $device_num "$model_name" "$data_encoding"
