#!/usr/bin/env bash

device_num=${1-0}
model_name="${2:-transformer}"
data_encoding="${3:-bra}"
data_dir="${4:-/mnt/disk1/datasets/alyx}"

config_file="${model_name}_${data_encoding}.yaml"

echo "-------------------------------------------"
echo "Starting training experiment"
echo "device: $device_num"
echo "model: $model_name"
echo "data encoding: $data_encoding"
echo "config file: $config_file"
echo "data directory: $data_dir"
echo "-------------------------------------------"

CUDA_VISIBLE_DEVICES=$device_num \
HYDRA_FULL_ERROR=1 \
uv run run.py -m \
  +experiments/who_is_alyx="$config_file" \
  seed=1,2,42 \
  data_dir="$data_dir"

