#!/usr/bin/env bash

model_name="${1:-transformer}"
data_encoding="${2:-bra}"
data_dir="${3:-/mnt/disk1/datasets/alyx}"

config_file="${model_name}_${data_encoding}.yaml"

echo "-------------------------------------------"
echo "Starting training experiment"
echo "model: $model_name"
echo "data encoding: $data_encoding"
echo "config file: $config_file"
echo "data directory: $data_dir"
echo "-------------------------------------------"

echo "Slurm assigned devices: $CUDA_VISIBLE_DEVICES"
echo "Slurm job GPUs: $SLURM_JOB_GPUS"

if command -v nvidia-smi &> /dev/null; then
  nvidia-smi --query-gpu=index,name,memory.total --format=csv
else
  echo "Warning: nvidia-smi not found. This node might not have GPU installed"
fi
echo "-------------------------------------------"

echo "-------------------------------------------"
echo "Multirun experiment"
echo "-------------------------------------------"

HYDRA_FULL_ERROR=1 \
python run.py -m \
  +experiments/who_is_alyx="$config_file" \
  seed=2,42 \
  data_dir="$data_dir"

