#!/usr/bin/env bash

device_num=${1-0}
model_name="${2:-transformer}"
data_encoding="${3:-bra}"
seed=${4:-1}
mode="${5:-train}"
data_dir="${6:-/mnt/disk1/datasets/alyx}"

config_file="${model_name}_${data_encoding}.yaml"

case "$mode" in
  "train")

    echo "-------------------------------------------"
    echo "Starting training experiment"
    echo "device: $device_num"
    echo "model: $model_name"
    echo "data encoding: $data_encoding"
    echo "seed: $seed"
    echo "config file: $config_file"
    echo "data directory: $data_dir"
    echo "-------------------------------------------"

    CUDA_VISIBLE_DEVICES=$device_num \
    HYDRA_FULL_ERROR=1 \
    python run.py \
      +experiments/who_is_alyx="$config_file" \
      seed=$seed \
      data_dir="$data_dir"

  ;;
  "test")

    echo "-------------------------------------------"
    echo "Starting test experiment"
    echo "device: $device_num"
    echo "model: $model_name"
    echo "data encoding: $data_encoding"
    echo "seed: $seed"
    echo "-------------------------------------------"

    CUDA_VISIBLE_DEVICES=$device_num \
    HYDRA_FULL_ERROR=1 \
    python run_test.py \
      +experiments/who_is_alyx="$config_file" \
      seed=$seed \
      data_dir="$data_dir"

  ;;
  *)
      echo "mode $mode not supported"
      exit 1

  ;;
esac
