#!/usr/bin/env bash

device_num=${1-0}
model_name="${2:-transformer}"
data_encoding="${3:-bra}"
seed=${4:-1}
data_dir="${5:-/mnt/disk1/datasets/alyx}"

config_file="${model_name}_${data_encoding}.yaml"

echo "-------------------------------------------"
echo "Starting training experiment"
echo "device: $device_num"
echo "model: $model_name"
echo "data encoding: $data_encoding"
echo "seed: $seed"
echo "config file: $config_file"
echo "data directory: $data_dir"
echo "-------------------------------------------"

CUDA_VISIBLE_DEVICES=$device_num \
HYDRA_FULL_ERROR=1 \
python run.py \
  +experiments/who_is_alyx="$config_file" \
  seed=$seed \
  data_dir="$data_dir"

echo "-------------------------------------------"
echo "Starting test experiment"
echo "-------------------------------------------"

CUDA_VISIBLE_DEVICES=$device_num \
HYDRA_FULL_ERROR=1 \
python run_test.py \
  +experiments/who_is_alyx="$config_file" \
  seed=$seed \
  data_dir="$data_dir"
