#!/usr/bin/env bash

device_num=${1-0}
model_name="${2:-transformer}"
data_encoding="${3:-bra}"
seed=${4:-1}
run_number=${5:-0}
mode="${6:-train}"
data_dir="${7:-/mnt/disk1/datasets/alyx}"

config_file="${model_name}_${data_encoding}.yaml"

case "$mode" in
  "train")

    echo "-------------------------------------------"
    echo "Starting training experiment"
    echo "device: $device_num"
    echo "model: $model_name"
    echo "data encoding: $data_encoding"
    echo "config file: $config_file"
    echo "data directory: $data_dir"
    echo "-------------------------------------------"

    CUDA_VISIBLE_DEVICES=$device_num \
    HYDRA_FULL_ERROR=1 \
    python run.py -m \
      +experiments/who_is_alyx="$config_file" \
      seed=1,2,42 \
      data_dir="$data_dir"

  ;;
  "test")

    echo "-------------------------------------------"
    echo "Starting full test experiment"
    echo "device: $device_num"
    echo "model: $model_name"
    echo "data encoding: $data_encoding"
    echo "-------------------------------------------"

    CUDA_VISIBLE_DEVICES=$device_num \
    HYDRA_FULL_ERROR=1 \
    python run_test.py -m \
      +experiments/who_is_alyx="$config_file" \
      seed=1,2,42 \
      run_number=0,1,2 \
      day_file_pos=1 \
      data_dir="$data_dir"

  ;;
  "test_single")

    echo "-------------------------------------------"
    echo "Starting single test experiment"
    echo "device: $device_num"
    echo "model: $model_name"
    echo "data encoding: $data_encoding"
    echo "seed: $seed"
    echo "run_number: $run_number"
    echo "-------------------------------------------"

    CUDA_VISIBLE_DEVICES=$device_num \
    HYDRA_FULL_ERROR=1 \
    python run_test.py \
      +experiments/who_is_alyx="$config_file" \
      seed=$seed \
      run_number=$run_number \
      data_dir="$data_dir"

  ;;
  *)
      echo "mode $mode not supported"
      exit 1

  ;;
esac
